"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./components/header/index");
require("./components/logo/index");
require("./components/footer/index");
require("./components/text/index");
require("./components/button/index");
require("./components/burger/index");
require("./components/menu-list/index");
require("./components/registration-form/index");
require("./components/pet-card/index");
require("./components/session-closer/index");
require("./components/custom-menu/index");
